  services:
    node-proxy-app:
      build:
        context: ./esignet-proxy
        dockerfile: Dockerfile
      container_name: node-proxy-app
      #ports:
      #  - "4000:4000"
      volumes:
        - ./esignet-proxy:/app
        - /app/node_modules
      networks:
      - cdpi_demo_network
      restart: always

    react-app:
      build:
        context: ./react-demo-app
        dockerfile: Dockerfile
      container_name: react-demo-app
      #ports:
      #  - "3001:80"
      networks:
      - cdpi_demo_network
      depends_on:
        - node-proxy-app
      restart: always

  networks:
    cdpi_demo_network:
      external: true