  services:
    node-proxy-app:
      build:
        context: ./esignet-proxy
        dockerfile: Dockerfile
      container_name: node-proxy-app
      #ports:
      #  - "4000:4000" # Mapea el puerto de tu app Node.js al host
      volumes:
        - ./esignet-proxy:/app
        - /app/node_modules
      networks:
      - cdpi_demo_network
      restart: always

    # NUEVOS SERVICIOS: Tu aplicación React (frontend)
    react-app:
      build:
        context: ./react-demo-app
        dockerfile: Dockerfile
      container_name: react-demo-app
      #ports:
      #  - "3001:80" # Mapea el puerto 80 del contenedor (Nginx) al puerto 3002 del host
      networks:
      - cdpi_demo_network
      depends_on:
        - node-proxy-app
      restart: always

  # Define la red externa
  networks:
    cdpi_demo_network:
      external: true